# Generated by Django 4.0.4 on 2022-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondsensor_reading',
            name='device_id1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor_reading',
            name='device_id',
            field=models.IntegerField(),
        ),
    ]
