# Generated by Django 4.0.4 on 2022-06-21 19:26

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_secondsensor_reading_device_id1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondsensor_reading',
            name='device_status1',
            field=models.BooleanField(default=True, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='secondsensor_reading',
            name='gas_analog_reading1',
            field=models.FloatField(default='0', max_length=20, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='secondsensor_reading',
            name='hum_reading1',
            field=models.FloatField(max_length=20, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='secondsensor_reading',
            name='temp_reading1',
            field=models.FloatField(max_length=20, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='sensor_reading',
            name='gas_analog_reading',
            field=models.FloatField(default='0', max_length=20, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='sensor_reading',
            name='hum_reading',
            field=models.FloatField(max_length=20, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='sensor_reading',
            name='temp_reading',
            field=models.FloatField(max_length=20, null=sqlalchemy.sql.expression.true),
        ),
    ]
