# Generated by Django 4.0.4 on 2022-06-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_secondsensor_reading_device_status1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondsensor_reading',
            name='device_status1',
            field=models.BooleanField(default=True),
        ),
    ]
