# Generated by Django 4.0.4 on 2022-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert_notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_detail', models.TextField()),
                ('read_by', models.BooleanField(default=False)),
            ],
        ),
    ]
