# Generated by Django 4.0.4 on 2022-06-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alert_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_notify',
            name='device_id',
            field=models.CharField(default='no alert', max_length=30),
        ),
    ]
