# Generated by Django 4.0.4 on 2022-06-30 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alert_notify_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 30, 18, 10, 4, 554581, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='alert_notify',
            name='device_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert_notify',
            name='gas_analog_reading',
            field=models.FloatField(default='0', max_length=20, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='alert_notify',
            name='hum_reading',
            field=models.FloatField(max_length=20, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='alert_notify',
            name='temp_reading',
            field=models.FloatField(max_length=20, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
