# Generated by Django 4.0.4 on 2022-06-30 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alert_notify_alert_time_alert_notify_device_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 30, 23, 43, 15, 628019)),
        ),
    ]
