# Generated by Django 4.0.4 on 2022-07-01 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_alert_notify_alert_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert_notify',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='alert_notify',
            name='device_status',
        ),
        migrations.RemoveField(
            model_name='alert_notify',
            name='gas_analog_reading',
        ),
        migrations.RemoveField(
            model_name='alert_notify',
            name='hum_reading',
        ),
        migrations.RemoveField(
            model_name='alert_notify',
            name='temp_reading',
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 2, 3, 47, 3, 140268)),
        ),
    ]
