# Generated by Django 4.0.4 on 2022-07-03 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alert_notify_device_id_alter_alert_notify_alert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='profile_images',
            field=models.ImageField(default=None, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 3, 21, 29, 37, 695366)),
        ),
    ]
