# Generated by Django 4.0.4 on 2022-07-03 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_login_profile_images_alter_alert_notify_alert_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='profile_images',
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 3, 21, 31, 21, 683062)),
        ),
    ]
