# Generated by Django 4.0.4 on 2022-07-03 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_alert_notify_alert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='profile_images',
            field=models.ImageField(default=None, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 3, 21, 33, 49, 433257)),
        ),
    ]
