# Generated by Django 4.0.4 on 2022-07-03 16:07

import datetime
from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_login_profile_images_alter_alert_notify_alert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 3, 21, 37, 56, 263036)),
        ),
        migrations.AlterField(
            model_name='login',
            name='profile_images',
            field=models.ImageField(blank=sqlalchemy.sql.expression.true, null=True, upload_to='profile_images'),
        ),
    ]
