# Generated by Django 4.0.4 on 2022-07-03 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_alert_notify_alert_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='profile_images',
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 3, 21, 41, 13, 178012)),
        ),
    ]
