# Generated by Django 4.0.4 on 2022-07-09 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_alert_notify_alert_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_alert_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('temp_reading', models.FloatField(max_length=20)),
                ('hum_reading', models.FloatField(max_length=20)),
                ('device_status', models.BooleanField(default=True)),
                ('gas_analog_reading', models.FloatField(max_length=20)),
                ('device_id1', models.IntegerField()),
                ('temp_reading1', models.FloatField(max_length=20)),
                ('hum_reading1', models.FloatField(max_length=20)),
                ('device_status1', models.BooleanField(default=True)),
                ('gas_analog_reading1', models.FloatField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 9, 10, 4, 24, 669138)),
        ),
    ]
