# Generated by Django 4.0.4 on 2022-07-09 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_remove_sensor_alert_values_device_id1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_alert_values',
            name='id',
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 9, 10, 10, 3, 181395)),
        ),
        migrations.AlterField(
            model_name='sensor_alert_values',
            name='device_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
