# Generated by Django 4.0.4 on 2022-07-09 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_remove_sensor_alert_values_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sensor_alert_values',
            new_name='master_node_alert_values',
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 9, 10, 12, 32, 841492)),
        ),
    ]
