# Generated by Django 4.0.4 on 2022-07-09 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_sub_node_alert_values_master_node_alert_values_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub_node_alert_values',
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 9, 11, 54, 28, 175411)),
        ),
    ]
