# Generated by Django 4.0.4 on 2022-07-09 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_delete_sub_node_alert_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_node_alert_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(default=2)),
                ('temp_reading1', models.FloatField(max_length=20)),
                ('hum_reading1', models.FloatField(max_length=20)),
                ('device_status', models.BooleanField(default=True)),
                ('gas_analog_reading1', models.FloatField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 9, 11, 55, 9, 516877)),
        ),
    ]
