# Generated by Django 4.0.4 on 2022-07-09 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_sub_node_alert_values_alter_alert_notify_alert_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='master_node_alert_values',
            new_name='node_alert_values',
        ),
        migrations.DeleteModel(
            name='sub_node_alert_values',
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 9, 11, 58, 42, 88695)),
        ),
    ]
