# Generated by Django 4.0.4 on 2022-07-09 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_rename_master_node_alert_values_node_alert_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 9, 11, 59, 25, 672460)),
        ),
        migrations.AlterField(
            model_name='node_alert_values',
            name='device_id',
            field=models.IntegerField(),
        ),
    ]
