# Generated by Django 4.0.4 on 2022-07-16 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_alter_alert_notify_alert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_alert_values',
            name='alert_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='node_alert_values',
            name='alert_time',
            field=models.TimeField(default='20:29:12'),
        ),
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default='20:29:12'),
        ),
    ]
