# Generated by Django 4.0.4 on 2022-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_node_alert_values_alert_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_notify',
            name='alert_time',
            field=models.TimeField(default='16:42:57'),
        ),
        migrations.AlterField(
            model_name='node_alert_values',
            name='alert_time',
            field=models.TimeField(default='16:42:57'),
        ),
    ]
